// GENERATED — do not hand-edit. Transcribed verbatim from Eva's audited master:
//   'Pediatrics_LEK_358_Audited_Corrected_Master_2026_with_Charts.docx' (16 Aug 2026)
// Manus flattened these OPTION/STATUS tables out when it built cards.ts, which left
// several answers referring to a 'table above' that was not on the card. This restores
// them. Card id N corresponds to master question QN (verified: 358/358 stems match).
//
// correct: true  = the master marks the option TRUE  (green)
// correct: false = the master marks it FALSE / EXCLUDED (red) — the answer to an EXCEPT stem

export type CardOption = { letter: string; text: string; correct: boolean };

export const cardOptions: Record<number, CardOption[]> = {
  4: [
    { letter: "A", text: "respiratory distress requiring intubation and mechanical ventilation", correct: true },
    { letter: "B", text: "pulmonary hypertension", correct: true },
    { letter: "C", text: "osteitis", correct: false },
    { letter: "D", text: "septic shock", correct: true },
    { letter: "E", text: "meningitis", correct: true },
  ],
  16: [
    { letter: "A", text: "excess of phosphates in the diet", correct: true },
    { letter: "B", text: "osteopenia of prematurity", correct: true },
    { letter: "C", text: "osteogenesis imperfecta", correct: true },
    { letter: "D", text: "Ehlers-Danlos syndrome", correct: false },
    { letter: "E", text: "Down syndrome", correct: true },
  ],
  38: [
    { letter: "A", text: "ultrasound image suggesting a proliferating lesion", correct: true },
    { letter: "B", text: "adenopathy of supra- and subclavicular lymph nodes", correct: true },
    { letter: "C", text: "adenopathy accompanied by general symptoms: weight loss, fever without infection, pruritus", correct: true },
    { letter: "D", text: "neck lymph node enlargement lasting for a week, accompanying pharyngitis", correct: false },
    { letter: "E", text: "painless lymph node, growing for several weeks without symptoms of infection", correct: true },
  ],
  41: [
    { letter: "A", text: "age between 4 and 12", correct: true },
    { letter: "B", text: "pain does not occur daily", correct: true },
    { letter: "C", text: "pain always occurs in the evening or night, it never occurs in the morning", correct: true },
    { letter: "D", text: "positive family history of growing pains", correct: false },
    { letter: "E", text: "pain is symmetrical and involves thighs, popliteal regions and lower legs", correct: true },
  ],
  44: [
    { letter: "A", text: "DiGeorge syndrome", correct: true },
    { letter: "B", text: "autoimmune polyendocrine syndrome type 1", correct: true },
    { letter: "C", text: "hyperparathyroidism in a pregnant mother", correct: true },
    { letter: "D", text: "condition after neck irradiation", correct: true },
    { letter: "E", text: "CaSR inactivating mutation", correct: false },
  ],
  45: [
    { letter: "A", text: "hypercalciuria", correct: true },
    { letter: "B", text: "hypocitraturia", correct: true },
    { letter: "C", text: "hyperoxaluria", correct: true },
    { letter: "D", text: "hypermagnesuria", correct: false },
    { letter: "E", text: "hyperuricosuria", correct: true },
  ],
  69: [
    { letter: "A", text: "leptin deficiency", correct: true },
    { letter: "B", text: "leprechaunism", correct: false },
    { letter: "C", text: "overeating", correct: true },
    { letter: "D", text: "hypercortisolemia", correct: true },
    { letter: "E", text: "Prader-Willi syndrome", correct: true },
  ],
  75: [
    { letter: "A", text: "mother’s underweight before pregnancy", correct: true },
    { letter: "B", text: "mother’s age under 16 years", correct: true },
    { letter: "C", text: "mother’s obesity or high weight gain during pregnancy", correct: true },
    { letter: "D", text: "mother’s diet rich in folic acid", correct: false },
    { letter: "E", text: "gestational diabetes", correct: true },
  ],
  88: [
    { letter: "A", text: "location on the BMI centile chart", correct: true },
    { letter: "B", text: "waist-to-hip ratio (WHR). 12 12 12 12", correct: true },
    { letter: "C", text: "abdominal circumference chart", correct: true },
    { letter: "D", text: "Cole’s index", correct: true },
    { letter: "E", text: "crown-rump length (CRL)", correct: false },
  ],
  94: [
    { letter: "A", text: "mucus discharge in the nasal passages", correct: false },
    { letter: "B", text: "fibrous debris in the tonsillar crypts", correct: true },
    { letter: "C", text: "enlarged and painful submandibular lymph nodes", correct: true },
    { letter: "D", text: "petechiae on the palatal mucosa", correct: true },
    { letter: "E", text: "scarlet-fever-like skin rash, dawn effect", correct: true },
  ],
  100: [
    { letter: "A", text: "mesodermal and neuroectodermal dysplasia", correct: true },
    { letter: "B", text: "neurofibromatosis", correct: true },
    { letter: "C", text: "cerebral hemangiomas", correct: true },
    { letter: "D", text: "Bourneville's disease", correct: true },
    { letter: "E", text: "Tay-Sachs disease", correct: false },
  ],
  103: [
    { letter: "A", text: "achondroplasia", correct: true },
    { letter: "B", text: "Marfan syndrome", correct: false },
    { letter: "C", text: "Down syndrome", correct: true },
    { letter: "D", text: "Turner syndrome", correct: true },
    { letter: "E", text: "fetal alcohol syndrome", correct: true },
  ],
  108: [
    { letter: "A", text: "increased vulnerability to opportunistic infections", correct: true },
    { letter: "B", text: "graft versus host disease", correct: false },
    { letter: "C", text: "acute or chronic rejection of the graft", correct: true },
    { letter: "D", text: "development of lymphoproliferative diseases and lymphomas", correct: true },
    { letter: "E", text: "relapse of underlying disease", correct: true },
  ],
  111: [
    { letter: "A", text: "non-alcoholic fatty liver disease", correct: true },
    { letter: "B", text: "Kawasaki disease", correct: true },
    { letter: "C", text: "Duchenne muscular dystrophy", correct: true },
    { letter: "D", text: "iron-deficiency anemia", correct: false },
    { letter: "E", text: "acute hepatitis", correct: true },
  ],
  116: [
    { letter: "A", text: "newborn with spinal dysraphism", correct: false },
    { letter: "B", text: "neonate with sepsis", correct: true },
    { letter: "C", text: "1-year-old child after an episode of complex seizures", correct: true },
    { letter: "D", text: "2-year-old child with the suspicion of leukodystrophy", correct: true },
    { letter: "E", text: "3-year-old child with a neoplastic disease of the central nervous system", correct: true },
  ],
  118: [
    { letter: "A", text: "celiac disease", correct: true },
    { letter: "B", text: "hypothyroidism", correct: true },
    { letter: "C", text: "adrenal insufficiency", correct: false },
    { letter: "D", text: "Cushing’s syndrome", correct: true },
    { letter: "E", text: "chronic kidney disease", correct: true },
  ],
  123: [
    { letter: "A", text: "it is an autosomal dominantly inherited disease", correct: true },
    { letter: "B", text: "there is an abnormal development of liver, heart and kidneys", correct: true },
    { letter: "C", text: "there are increased levels of alkaline phosphatase", correct: true },
    { letter: "D", text: "there are craniofacial defects, spine defects (butterfly vertebrae)", correct: true },
    { letter: "E", text: "elevated total bilirubin levels, with a predominance of indirect", correct: false },
  ],
  125: [
    { letter: "A", text: "cystic fibrosis. 3 3", correct: true },
    { letter: "B", text: "primary ciliary dyskinesia", correct: true },
    { letter: "C", text: "plastic bronchitis", correct: true },
    { letter: "D", text: "pertussis", correct: false },
    { letter: "E", text: "bronchiectasis", correct: true },
  ],
  139: [
    { letter: "A", text: "impetigo is the most common bacterial infection in children", correct: true },
    { letter: "B", text: "in many cases it is caused by beta-hemolytic streptococcal infection", correct: true },
    { letter: "C", text: "erythema, followed by blisters and honey and yellow crusts occur", correct: true },
    { letter: "D", text: "glomerulonephritis may be a complication of impetigo", correct: true },
    { letter: "E", text: "Lisch nodules are found in more than 90% of patients with impetigo", correct: false },
  ],
  142: [
    { letter: "A", text: "Kawasaki disease", correct: true },
    { letter: "B", text: "elongated QT syndrome", correct: true },
    { letter: "C", text: "pulmonary hypertension", correct: true },
    { letter: "D", text: "abnormal self-regulation of heart rate and blood pressure during long time standing", correct: false },
    { letter: "E", text: "dilated cardiomyopathy", correct: true },
  ],
  143: [
    { letter: "A", text: "recurrence of pneumonia in the same localization", correct: true },
    { letter: "B", text: "pneumonia resistant to routine treatment", correct: true },
    { letter: "C", text: "atelectasis", correct: true },
    { letter: "D", text: "pain that increases with neck movements", correct: false },
    { letter: "E", text: "asymmetry of vesicular murmur", correct: true },
  ],
  147: [
    { letter: "A", text: "Down syndrome", correct: true },
    { letter: "B", text: "Beckwith-Wiedemann syndrome", correct: true },
    { letter: "C", text: "Nijmegen breakage syndrome", correct: true },
    { letter: "D", text: "neurofibromatosis type I", correct: true },
    { letter: "E", text: "familial Mediterranean fever", correct: false },
  ],
  150: [
    { letter: "A", text: "dilation of the renal pelvis and calyces observed in ultrasound imaging", correct: false },
    { letter: "B", text: "presence of nitrites in urine", correct: true },
    { letter: "C", text: "abnormal leukocyte count in urine", correct: true },
    { letter: "D", text: "bacteriuria", correct: true },
    { letter: "E", text: "dysuria and frequent urination", correct: true },
  ],
  160: [
    { letter: "A", text: "measles", correct: true },
    { letter: "B", text: "varicella", correct: true },
    { letter: "C", text: "rubella (German measles)", correct: true },
    { letter: "D", text: "infectious mononucleosis", correct: false },
    { letter: "E", text: "rotavirus diarrhea", correct: true },
  ],
  164: [
    { letter: "A", text: "risk of developing the disease is greater in preterm newborns", correct: true },
    { letter: "B", text: "risk of developing the disease is greater in female newborns", correct: false },
    { letter: "C", text: "infection most often develops via the ascending pathway", correct: true },
    { letter: "D", text: "UTI is most often caused by E. coli, but in teens Staphylococcus saprophyticus infection may occur", correct: true },
    { letter: "E", text: "phimosis can predispose to infections", correct: true },
  ],
  181: [
    { letter: "A", text: "hives is not accompanied by anaphylactic shock", correct: false },
    { letter: "B", text: "primary lesion in hives is a blister", correct: true },
    { letter: "C", text: "hives may be caused, among others, by neoplastic or connective tissue disease", correct: true },
    { letter: "D", text: "most important medications in treatment of hives are 2 generation antihistamines", correct: true },
    { letter: "E", text: "symptoms of chronic hives may accompany coeliac disease", correct: true },
  ],
  185: [
    { letter: "A", text: "it occurs in children under two years of age, principally during the fall and winter", correct: true },
    { letter: "B", text: "it has a biphasic course, after 2-3 days of acute upper respiratory tract infection the inspiratory and expiratory dyspnea occurs", correct: true },
    { letter: "C", text: "physical examination shows an inspiratory position of the chest, hyper-resonant percussion sound, wheezing and crackles, silent vesicular sound", correct: true },
    { letter: "D", text: "its treatment usually involves a broad-spectrum antibiotic, bronchodilators, high doses of glucocorticosteroids", correct: false },
    { letter: "E", text: "most important part of the management is proper hydration, oxygen therapy and air humidification", correct: true },
  ],
  193: [
    { letter: "A", text: "hemoptysis", correct: true },
    { letter: "B", text: "chronic infection with Mycoplasma pneumoniae and/or Chlamydia trachomatis", correct: false },
    { letter: "C", text: "changes in X-ray: recurrent atelectasis, bronchiectasis", correct: true },
    { letter: "D", text: "nasal polyps", correct: true },
    { letter: "E", text: "chronic sinusitis", correct: true },
  ],
  205: [
    { letter: "A", text: "it is recommended for anyone who stayed in the patient’s home or slept in the same room during 7 days before the onset of the symptoms", correct: true },
    { letter: "B", text: "vaccination should be considered in not vaccinated children", correct: true },
    { letter: "C", text: "it consists in acyclovir given orally at a dose of 4 x 200 mg", correct: false },
    { letter: "D", text: "it should be applied to close contact persons preferably within 24 hours, but not later than 2 weeks after the onset of the symptoms", correct: true },
    { letter: "E", text: "children should receive rifampicin or ceftriaxone", correct: true },
  ],
  211: [
    { letter: "A", text: "cardiac arrhythmia", correct: true },
    { letter: "B", text: "increased serum glucose concentration", correct: true },
    { letter: "C", text: "decreased muscle strength", correct: true },
    { letter: "D", text: "increased cholesterol concentration", correct: false },
    { letter: "E", text: "menstrual disorders", correct: true },
  ],
  225: [
    { letter: "A", text: "catarrhal stage is the period of the highest infectivity", correct: true },
    { letter: "B", text: "vaccination or being ill gives permanent immunity", correct: false },
    { letter: "C", text: "macrolides are the drug of choice", correct: true },
    { letter: "D", text: "cough can last up to half a year", correct: true },
    { letter: "E", text: "mental retardation, deafness and epilepsy are permanent after-effects", correct: true },
  ],
  228: [
    { letter: "A", text: "abdominal pain", correct: true },
    { letter: "B", text: "vomiting", correct: true },
    { letter: "C", text: "dehydration", correct: true },
    { letter: "D", text: "hypovolemia", correct: true },
    { letter: "E", text: "hyperglycemia", correct: false },
  ],
  232: [
    { letter: "A", text: "active tuberculosis in the mother", correct: true },
    { letter: "B", text: "HIV infection in the mother", correct: true },
    { letter: "C", text: "herpes simplex infection of the nipple or an areola of the mamma", correct: true },
    { letter: "D", text: "chronic hepatitis C in the mother", correct: false },
    { letter: "E", text: "cytostatic treatment of the mother", correct: true },
  ],
  236: [
    { letter: "A", text: "weight loss", correct: true },
    { letter: "B", text: "coughing attacks at night with dyspnoea", correct: true },
    { letter: "C", text: "heartburn", correct: false },
    { letter: "D", text: "swallowing disorders", correct: true },
    { letter: "E", text: "anaemia", correct: true },
  ],
  237: [
    { letter: "A", text: "proteinuria and hematuria are necessary for the diagnosis", correct: false },
    { letter: "B", text: "incidence in boys is higher than in girls", correct: true },
    { letter: "C", text: "medication antigens may induce the disease", correct: true },
    { letter: "D", text: "benign forms, without nephropathy symptoms, are self-limiting", correct: true },
    { letter: "E", text: "disease is related to the presence of viral or bacterial antigens", correct: true },
  ],
  241: [
    { letter: "A", text: "osteoporosis", correct: true },
    { letter: "B", text: "recurrent peptic ulcer", correct: true },
    { letter: "C", text: "cirrhosis of the liver", correct: false },
    { letter: "D", text: "recurrent pancreatitis with lithiasis", correct: true },
    { letter: "E", text: "polyuria and a tendency towards urinary tract infections", correct: true },
  ],
  245: [
    { letter: "A", text: "pathological changes within joints (inflammation, edema, pain with limited range of motion)", correct: true },
    { letter: "B", text: "diffuse colicky abdominal pain", correct: true },
    { letter: "C", text: "proteinuria or the presence of albumin in urine collected after the night", correct: true },
    { letter: "D", text: "haematuria or erythrocyturia", correct: true },
    { letter: "E", text: "enlargement of the spleen", correct: false },
  ],
  248: [
    { letter: "A", text: "headaches and dizziness", correct: true },
    { letter: "B", text: "weakness", correct: true },
    { letter: "C", text: "cardiac systolic murmur", correct: true },
    { letter: "D", text: "angular cheilitis", correct: true },
    { letter: "E", text: "bradycardia", correct: false },
  ],
  251: [
    { letter: "A", text: "it is an etiological factor of erythema contagiosum", correct: false },
    { letter: "B", text: "most commonly it affects children under 2 years of age", correct: true },
    { letter: "C", text: "fever seizures may be observed in the course of the disease", correct: true },
    { letter: "D", text: "typical sign of the infection in a complete blood count is neutropenia", correct: true },
    { letter: "E", text: "characteristic sign of the infection is a maculopapular rash on the face and torso", correct: true },
  ],
  252: [
    { letter: "A", text: "bilateral conjunctival injection", correct: true },
    { letter: "B", text: "cracked or fissured lips", correct: true },
    { letter: "C", text: "generalized polymorphous rash", correct: true },
    { letter: "D", text: "thrombocytopenia", correct: false },
    { letter: "E", text: "cervical lymph node painful enlargement", correct: true },
  ],
  255: [
    { letter: "A", text: "meningitis", correct: true },
    { letter: "B", text: "myocarditis and pericarditis", correct: true },
    { letter: "C", text: "hand, foot and mouth disease", correct: true },
    { letter: "D", text: "herpangina", correct: true },
    { letter: "E", text: "influenza", correct: false },
  ],
  257: [
    { letter: "A", text: "overdosage of vitamin D", correct: true },
    { letter: "B", text: "necrosis of subcutaneous adipose tissue", correct: true },
    { letter: "C", text: "immobilization", correct: true },
    { letter: "D", text: "neuroblastoma", correct: true },
    { letter: "E", text: "hypoparathyroidism", correct: false },
  ],
  260: [
    { letter: "A", text: "BCG vaccination should be postponed until the body weight has reached 2000 g", correct: true },
    { letter: "B", text: "vaccination against hepatitis B should be postponed until the body weight has reached 2000 g", correct: false },
    { letter: "C", text: "as a mandatory vaccination against diphtheria, tetanus and pertussis a vaccine with an acellular pertussis component should be used", correct: true },
    { letter: "D", text: "as a mandatory vaccination the child should receive a conjugated pneumococcal vaccine", correct: true },
    { letter: "E", text: "vaccination against measles, mumps and rubella should be given according to the chronological age", correct: true },
  ],
  262: [
    { letter: "A", text: "pentamidine", correct: true },
    { letter: "B", text: "L-asparaginase", correct: true },
    { letter: "C", text: "cyclosporine A", correct: true },
    { letter: "D", text: "prednisone", correct: true },
    { letter: "E", text: "vildagliptin", correct: false },
  ],
  284: [
    { letter: "A", text: "dermal lesions may be asymmetric and occur not only at the contact site but also at distant parts of the body", correct: true },
    { letter: "B", text: "type IV of immune response is involved in the development of allergic contact dermatitis", correct: true },
    { letter: "C", text: "the symptoms develop within 15-30 min. after exposure to allergen", correct: false },
    { letter: "D", text: "glucocorticosteroids and calcineurin inhibitors are used in therapy", correct: true },
    { letter: "E", text: "dermal lesions are accompanied by itching", correct: true },
  ],
  291: [
    { letter: "A", text: "fever lasting for more than 5 days", correct: true },
    { letter: "B", text: "erythema of the hands and feet", correct: true },
    { letter: "C", text: "bilateral conjunctivitis", correct: true },
    { letter: "D", text: "lip swelling and cracking", correct: true },
    { letter: "E", text: "pneumonia", correct: false },
  ],
  296: [
    { letter: "A", text: "excision biopsy of enlarged lymph node", correct: true },
    { letter: "B", text: "detecting Hodgkin/Reed-Sternberg cells in histopathology (HRS)", correct: true },
    { letter: "C", text: "fine-needle aspiration biopsy of lymph node", correct: false },
    { letter: "D", text: "bone marrow biopsy in patients in an advanced stage of the disease", correct: true },
    { letter: "E", text: "diagnostic imaging, including positron emission tomography (PET)", correct: true },
  ],
  299: [
    { letter: "A", text: "children who were not vaccinated at the age of 6 years can only be given the misssing vaccination at the age of 10 years", correct: false },
    { letter: "B", text: "an earlier vaccination with a vaccine against measles is not a contraindication for a vaccination with a combined measles, mumps and rubella vaccine (MMR vaccine)", correct: true },
    { letter: "C", text: "children who were administered two doses of a combined measles, mumps and rubella vaccine (MMR vaccine) in the previous years of their lives, do not require administration of the third dose of the vaccine", correct: true },
    { letter: "D", text: "a past medical history of measles, mumps and rubella does not constitute a contraindication for vaccination", correct: true },
    { letter: "E", text: "a vaccination with a combined measles, mumps and rubella vaccine (MMR vaccine) is not recommended 4 weeks prior to a planned pregnancy", correct: true },
  ],
  312: [
    { letter: "A", text: "a 10-20% salicylic ointment", correct: true },
    { letter: "B", text: "a 5-10% lactic acid ointment", correct: true },
    { letter: "C", text: "a 1% mupirocin ointment", correct: false },
    { letter: "D", text: "a preparation with dimethyl sulfoxide. 2 3- 2", correct: true },
    { letter: "E", text: "a preparation with 5-fluorouracil", correct: true },
  ],
  319: [
    { letter: "A", text: "in small children it occurs quite often but has a mild course", correct: false },
    { letter: "B", text: "macrolides are the treatment of choice", correct: true },
    { letter: "C", text: "the infection spreads by warm water and is facilitated by inhaling moist aerosols", correct: true },
    { letter: "D", text: "patient isolation is not necessary", correct: true },
    { letter: "E", text: "the usual onset is between 1 and 10 days after exposure", correct: true },
  ],
  320: [
    { letter: "A", text: "proctitis", correct: true },
    { letter: "B", text: "streptococcal pharyngitis", correct: true },
    { letter: "C", text: "lichen planus", correct: false },
    { letter: "D", text: "erysipelas", correct: true },
    { letter: "E", text: "scarlet fever", correct: true },
  ],
  338: [
    { letter: "A", text: "it is commonly referred to as “Wilms’ tumour”", correct: true },
    { letter: "B", text: "the basis for initiating treatment is a diagnostic biopsy with histologic examination", correct: false },
    { letter: "C", text: "treatment involves preoperative chemotherapy", correct: true },
    { letter: "D", text: "5-year survival rate for stage I nephroblastoma is &gt;95%", correct: true },
    { letter: "E", text: "stage V nephroblastoma refers to bilateral kidney involvement", correct: true },
  ],
  343: [
    { letter: "A", text: "antithrombin deficiency", correct: true },
    { letter: "B", text: "protein C deficiency", correct: true },
    { letter: "C", text: "protein S deficiency", correct: true },
    { letter: "D", text: "activated protein C (APC) resistance", correct: true },
    { letter: "E", text: "haemophilia A", correct: false },
  ],
  345: [
    { letter: "A", text: "all stages are subdivided into stages A and B", correct: true },
    { letter: "B", text: "the general symptoms used for the classification into stages A and B in the course of the clinical staging of Hodgkin lymphoma include body weight loss of &gt;10% over the last 6 months, unexplained fever of &gt;38°C, night sweat", correct: true },
    { letter: "C", text: "the classification into stage A is based on the absence of general symptoms", correct: true },
    { letter: "D", text: "stage IV refers to a diffuse or disseminated involvement of one or more extralymphatic organs, with or without involvement of the lymph nodes", correct: true },
    { letter: "E", text: "stage V refers to the spread to the central nervous system and cerebrospinal fluid, involvement of the lymph nodes on both sides of the diaphragm, and malignant pleural or peritoneal effusion without any other extralymphatic lesions", correct: false },
  ],
  346: [
    { letter: "A", text: "viral infections, such as viral hepatitis, can be the renal cause of acute renal failure", correct: true },
    { letter: "B", text: "the use of sulfonamides is the most common pre-renal cause of acute renal failure", correct: false },
    { letter: "C", text: "dehydration and an insufficient fluid intake is the pre-renal cause of acute renal failure", correct: true },
    { letter: "D", text: "the most common causes of acute renal failure are pre-renal causes (about 70%)", correct: true },
    { letter: "E", text: "congenital urinary abnormalities, such as structural anomalies of the urinary tract, predispose to extrarenal acute renal failure", correct: true },
  ],
  355: [
    { letter: "A", text: "the symptoms of PFAPA include: fever, aphthae, pharyngitis, lymphadenitis, and abdominal pain", correct: true },
    { letter: "B", text: "the gene responsible for the occurrence of PFAPA is ABC1", correct: false },
    { letter: "C", text: "the onset of PFAPA symptoms typically occurs before the age of 5", correct: true },
    { letter: "D", text: "the occurrence of PFAPA is not limited to a specific continent-it is a worldwide condition", correct: true },
    { letter: "E", text: "the prognosis is good", correct: true },
  ],
};
